bdaiinstitute/spot_ros2

spot_driver/spot_driver/spot_wrapper.py

This change helped me resolve the issue that 
the spot process keeps dying after launching.

Increase timeout to 10 sec (from 3 sec)

---

spot_driver/spot_driver/conversions.py

This corresponds to the newest version of [bosdyn_msgs](https://github.com/bdaiinstitute/bosdyn_msgs) where I've fixed enum and recursive message handling and fixed a bug in how conversions of maps worked.  Updating our internal docker container for these new messages is [here](https://github.com/bdaiinstitute/infrastructure/pull/18) and the changes to proto2ros and using this branch for BDAI are [here](https://github.com/bdaiinstitute/bdai/pull/86).
The conversion file that has been changed here was automatically generated (note: it should probably move to the `bosdyn_msgs` package rather than living here).

Updated conversions file that fixes enum handling

---

spot_driver/spot_driver/ros_helpers.py

As with many ROS2 things, this is fragile depending on the way the user has their nodes and executors set up :(

Adds waiting for all TF errors if timeout is specified in lookup_a_tform_b

---

README.md
spot_driver/launch/point_cloud_xyzrgb.launch.py
spot_driver/launch/spot_driver.launch.py
spot_driver/launch/spot_driver_with_namespace.launch.py
spot_driver/launch/spot_image_publishers.launch.py
spot_driver/setup.py
spot_driver/spot_driver/publish_camera.py
spot_driver/spot_driver/publish_cameras.py
spot_driver/spot_driver/ros_helpers.py
spot_driver/spot_driver/spot_ros2.py
spot_driver/spot_driver/spot_wrapper.py

The current publisher for RGB and depth images is slow. I have made the following improvements
- Added publishing the correct scoped frame_id for images
- Removed image publishing from spot_ros2.py and created a separate node to publish rgb, depth, or depth_registered
- Added arguments to publish depth_registered or depth aligned with the rgb frame

Fix publishing of images

---

.gitmodules

This fixes the submodule pointing to the wrong repository and includes the most recent commit in the bdaiinstitute repo.

Move spot_wrapper to bdaiinstitute repo

---

spot_driver/spot_driver/spot_ros2.py

This commit should have been in the previous PR and sets the spot_driver to use the same ros_helper function as the one that is now used by the image publisher

Missing commit from PR #45

---

spot_driver/spot_driver/spot_ros2.py

The `has_arm` parameter was hidden under a conditional and wasn't accessible unless you were publishing `depth_registered` images. Unindented and now we can access this parameter.

Fixed has_arm

---

spot_driver/spot_driver/spot_ros2.py

This PR adds a new ROS2 parameter to spot_ros2, called `cameras_used` of type list, that allows a user to specify which cameras they want image publishing for. 
Currently, spot_ros2 would publish images for all cameras, which can be unnecessary and slows things down, especially when the images are expensive to retrieve from Spot (like registered depth images).
By default, `cameras_used` is set to all cameras. So it is `["frontleft", "frontright", "left", "right", "back"]` when the robot has no arm, and plus `["hand"]` if the robot does have an arm.
For example, leaving `cameras_used` to be its default, the image topics are:
```
/Gosu/camera/back/camera_info
/Gosu/camera/back/image
/Gosu/camera/frontleft/camera_info
/Gosu/camera/frontleft/image
/Gosu/camera/frontright/camera_info …
```

[SW-127] Configure cameras to use in spot ros2

---

spot_driver/launch/spot_driver.launch.py
spot_driver/launch/spot_driver_with_namespace.launch.py

When I add publish_depth_registered: True in spot_ros.yaml, this parameter on spot_ros2 is still False. 
```
$ ros2 param get /Gosu/spot_ros2 publish_depth_registered
Boolean value is: False
```
I tried adding a print statement inside spot_ros2, and indeed, I get False for `publish_depth_registered`.
However, for some other parameters, like `auto_claim`, auto_stand, I am able to change their values in spot_ros.yaml file and have them reflected in the spot_ros2 node.
Similarly, I tried adding a print statement inside spot_ros2 to test for auto_stand and it works.
In `spot_driver_with_namespace.launch.py` and `spot_driver.launch.py`, the default value of the parameter `publish_depth_registered` (False) overwrites the parameter set in the YAML configuration file.
Remove `drivers_params` …

Fix publish_depth_registered overwritten in spot_ros2

---

.gitmodules
install_spot_ros2.sh

HTTPS submodules are preferred for public distribution because they don't require additional setup and SSH may be blocked on some networks.
I also added `-y` to the `apt install` command to make things smoother e.g. when running in a Docker build.

Use https submodule

---

spot_driver/spot_driver/spot_ros2.py

Extremely simple fix to make spot_wrapper log robot-specific too.
Now that logging within spot_wrapper is working, you get logs like:
```
[spot_ros2-1] [INFO] [1683750769.364323221] [Gosu.spot_ros2]: Starting ROS driver for Spot for Gosu
[spot_ros2-1] [INFO] [1683750769.365105183] [spot_wrapper]: Initialising robot at 10.17.30.31
[spot_ros2-1] [INFO] [1683750769.365348574] [spot_wrapper]: Trying to authenticate with robot...
[spot_ros2-1] [INFO] [1683750770.994341303] [spot_wrapper]: Successfully authenticated.
[spot_ros2-1] [INFO] [1683750770.995229933] [spot_wrapper]: Creating clients...
[spot_ros2-1] [INFO] [1683750770.998374009] [spot_wrapper]: No point cloud services are available.
```
The hope of this PR is to also add robot name to the [spot_wrapper] so that this works better for a …

[SW-143] Add Spot name to the wrapper logger name 

---

spot_driver/spot_driver/spot_ros2.py

There is a typo when initializing the camera info publisher for registered depth images. This caused the `publish_depth_registered_images_callback` callback to fail due to exception. After fixing this typo, the callback works. I can receive registered depth images at around 1-3hz.

[N/A] Fixing typo in depth registered info pub creation

---

spot_driver/setup.cfg

When running `colcon` you'll get a warning about a `script-dir` and `install-scripts` will not be supported in future versions and to use the underscored versions. Small fix just to cut down on warnings that pop up during building the package.

Fix setuptools future deprecation in setup.cfg file

---

.devcontainer/Dockerfile
README.md
install_spot_ros2.sh
spot_driver/spot_driver/conversions.py

This PR updates the install scripts to use the latest release from the [bosdyn_msgs](https://github.com/bdaiinstitute/bosdyn_msgs/releases/tag/v3.2.0-frametreesnapshot) repo. The updated package only adds the FrameTreeSnapshot parameter to various msgs. Previously it was ignored, but it is needed for some of the Manipulation API requests. 
Additionally, this PR updates `conversions.py` to the matching version that can handle the FrameTreeSnapshot parameters.

[N/A] Updated for new bosdyn_msgs that have frametreesnapshot

---

spot_driver/spot_driver/conversions.py

This fixes a bug from the proto2ros conversion. 
protobufs allow submessages e.g.
```
message Outside
{
message Inside
{
...
}
}
```
whereas ros msgs do not. When we generate the ros msgs we concatenate the message names, so the inner message would make a ros msg file for `OutsideInside`. protobuf also allows for `map`s whereas ros msgs do not, so we create a `Key<key-type>Value<value-type>` ros msg file. Previous proto2ros was not using the concatenated name for the import when converting a type that contained a map. It now does and this is the result. This specifically is need to use some of the manipulation API

[SW-232] Fixed conversions for map values which was submsgs from the protobuf

---

spot_driver/spot_driver/conversions.py

@jbarry-bdai mentioned that in protobufs messages can reference submessages that are later in the file than they are. This is the result of improving the fix from #95 in our autogeneration script to handle that case. Luckily it found some more bugs that we had yet to discover.
Also, I checked and there is in fact a `KeyStringValueBosdynMsgsNavigationFeedbackResponseActiveRegionInformation.msg`

[SW-232] Fixed bug in autogeneration of conversions.py 

---

spot_driver/spot_driver/spot_ros2.py

The default robot state task rate is 50 Hz (in code at least) but gets throttled because the async_tasks_rate is lower. This increases the default to match the largest individual callback rate. It also changes it to explicitly be a float, so a float can be used for the ros parameter.

[N/A] Increased default rate to be the same as the largest individual task rate and set to float

---

spot_driver/spot_driver/spot_ros2.py

Previously the feedback's current state was being compared against protobufs when it should have been compared against ros msg values (created by autoconverting enums).
This was caught while debugging the grasp_in_image request

[N/A] Fixed manipulation_goal_complete function

---

spot_driver/spot_driver/spot_ros2.py

On any image callback, the `spot_driver` would call `populate_camera_static_transforms` to ensure all individual spot camera's calibration-specific static transforms were published. This assumed that all cameras are statically mounted (e.g. rigidly fixed to the body), but this is not true for arm/hand cameras.
Without this patch, the hand camera frames would be fixed to their first static transform (e.g. stowed position), and this would not update as the arm was unstowed or moved. This patch ensures that if an arm is present, the single dynamic transform (`arm0.link_wrl -> body`) is published dynamically on image callback, ensuring the rest of the kinematic chain for image frames are updated appropriately.
The normal robot state callback publishes dynamic transforms at robot state …

[SW-220] Publish non-static hand camera transform on image update

---

examples/simple_arm_motion/README.md
examples/simple_arm_motion/simple_arm_motion/arm_simple.py
examples/simple_walk_forward/README.md
examples/simple_walk_forward/simple_walk_forward/walk_forward.py

The namespace for the robot wasn't included, causing an error where it wouldn't find the ROS topic it was supposed to publish to. I've added it to the example as a command line argument to pass in and updated the README

SW-276-fix-the-ros-walk-forward-example

---

spot_driver/spot_driver/spot_ros2.py
spot_driver/test/test_spot_driver.py

Tickets: SW-265, SW-255
Changes:
- Made Spot Ros 2 "Mock_spot" actually work as intended allowing services to be created (they already had checks for mock)
- Added unit tests and changes to spot_ros2.py to allow for that testing without a launch file
- To fix dependency issues, __init__.py needed moving into the tests folder so that it could properly find modules
- Cleaned up redundant code of the camera publishing using a partial and the common naming scheme (this does potentially change the topic name on the rgb camera images. Its cleaner if the spot_wrapper image name and the topic name match, but if it's a deal breaker I'm happy to put a check in to swap just that one to be "camera/..." instead of "visual/.." again)
Tests run:
- Ran on a spot testing out normal functionality as well …

[SW-265] Spot Ros2 slight refactor for testability and unit testing

---

spot_driver/spot_driver/ros_helpers.py
spot_driver/spot_driver/spot_ros2.py

This patch rolls back the changes made in #107 (see description for problem notes) in favor of a cleaner and simpler approach to handling `arm0.link_wr1` in hand camera image callbacks - with special case code to:
- avoid publishing a static transform for `arm0.link_wr1` at all as it is not static
- rename parent `arm0.link_wr1` to `link_wr1` in any static transforms for proper connectivity to robot state updates
- rely on robot state publication to handle all necessary dynamic tfs in a single place
This change will have no impact on spot configurations without an arm and will not break anything in the future if the naming discrepancy is fixed by Boston Dynamics.
Relying on robot state has the added benefit of much higher frequency tf updates, eliminating the choppy behavior seen when …

[SW-328] Better handling of arm0.link_wr1 for hand camera transforms

---

spot_driver/config/spot_ros_example.yaml
spot_driver/spot_driver/spot_ros2.py

Also updated the example config to represent these changes. The original `spot_ros2` publishing rate params are listed in a dictionary which isn't an accepted type by `rclpy`. I've changed it so that each publishing rate is separately listed and gets formed into the dictionary. I also remove unused publishing rates.

[SW-319] Updated spot_ros2 to get publishing rates from the config file. 

---

spot_driver/spot_driver/spot_ros2.py

This patch corrects a minor bug where the `list_world_objects` callback was attempting to invoke a non-existent function/endpoint on the `spot_wrapper` rather than one of its members.

[SW-324] Fix incorrect list_world_objects endpoint call

---

examples/simple_arm_motion/simple_arm_motion/arm_simple.py
examples/simple_walk_forward/simple_walk_forward/walk_forward.py

The examples would fail originally due to the ActionClientWrapper refactor requiring an action name and a goal. The previous examples only sent a goal. Added an action name for the `walk_forward` and `arm_simple` examples.

[SW-440] Fixed the goals by passing a name to them

---

spot_driver/spot_driver/spot_ros2.py

Want to double check: in the case that the robot has aborted a goal, do we also want to check and stop the robot from doing anything?

[SW-443] spot_ros2 does not tell the spot-sdk to cancel when an action is cancelled

---

spot_driver/spot_driver/spot_ros2.py
spot_msgs/CMakeLists.txt
spot_msgs/srv/GetGripperCameraParameters.srv
spot_msgs/srv/SetGripperCameraParameters.srv

This PR adds the services `GetGripperCameraParameter` and `SetGripperCameraParameter` as well as the corresponding callbacks needed to `Spot_ros2.py`. 
This PR depends on [another PR](https://github.com/bdaiinstitute/spot_wrapper/pull/71) to `spot_wrapper` that adds a wrapper around the gripper camera param python client.

Add ROS services for Get and Set Gripper Camera Param messages

---

examples/simple_arm_motion/README.md
examples/simple_walk_forward/README.md
spot_driver/launch/spot_driver.launch.py

This is a follow up PR to #125.
This PR changes the `rviz_config_filename` parameter to `rviz_config_file` and doesn't attempt to look for the rviz config inside of the `spot_driver` package. 
Also includes documentation changes that remove the reference to `spot_driver_with_namespace.launch.py`

Fix launch file param for RViz config filepath

---

spot_driver/spot_driver/manual_conversions.py

This was missing and is needed by some of the conversions in conversions.py

[N/A] Added manual conversion for FloatValue protobuf

---

spot_driver/spot_driver/spot_ros2.py

As referenced [here](https://github.com/boston-dynamics/spot-sdk/blob/6a03ae12056a74e65fd9715128e0c40762dfa7ba/python/bosdyn-client/src/bosdyn/client/async_tasks.py#L182), the logger on Spot expects a `logging.Logger` style logger with an exception field instead of the RCUtilsLogger. The RCUtilsLogger doens't have an `exception` method, so I just wrapped it with an exception method. 
This was HIL tested by calling the `_handle_error` in SpotWrapper's various classes that inherit from `AsyncPeriodicQuery`. This should log data for future failures in the robot's start up.

[SW-526] Added an exception field to the ROS2 logger for SpotWrapper

---

.github/dependabot.yml

This will configure dependabot to open PRs to update the submodules. It will check nightly. PRs will still have to be manually approved/merged.

[N/A] Add dependabot config to update submodules

---

spot_driver/test/test_spot_driver.py

This is the first of 3 PRs to refactor `_robot_command_goal_complete` so that is more readable and easier to maintain.
In this PR, we are adding a unit test to capture and verify the current logic of the function before refactoring it in order to prevent introducing any regressions. 
Writing the unit test also caught a few bugs and missing checks for some statuses which will be address in the final PR.
2nd PR: https://github.com/bdaiinstitute/spot_ros2/pull/167

[PN-68] add unit test for robot command goal complete

---

spot_driver/launch/spot_driver.launch.py
spot_driver/package.xml

Depends on #145.
- Launches the C++-based Spot image publisher node in the main Spot driver launch file.
- Disables the Python driver node's image publishing functionality, since this is replaced by the new image publisher node.

Add Spot C++ image publisher node to spot_driver.launch.py

---

spot_description/urdf/accessories.urdf.xacro
spot_description/urdf/spot_arm_macro.urdf
spot_description/urdf/spot_macro.xacro
spot_description/urdf/spot_simple.urdf.xacro

prior adds absolute paths of mesh files to /robot_description
the paths for a remote subscriber are different, and rviz2 fails to visualise the robot model the later avoids it

file://$(find spot_description) -> package://spot_description

---

spot_driver/spot_driver/spot_ros2.py
spot_driver/test/test_spot_driver.py

These feedback statuses were introduced with bosdyn_msgs 3.3.2. This PR updates the logic in `spot_ros2.py` and the tests.

Add logic for Arm Impedance feedback statuses

---

spot_driver_cpp/src/interfaces/spot_interface.cpp

This code:
`info_msg.d = std::vector<double>{5, 0.0};`
Creates a vector of length 2 with the contents [5.0, 0.0], which results in CameraInfo messages with the incorrect distortion coefficients. The new code correctly creates a message with a length-five distortion vector, filled with zeros.

Fix distortion coefficient vector

---

spot_driver/launch/spot_driver.launch.py
spot_driver/spot_driver/spot_ros2.py
spot_driver/test/test_spot_driver.py

This PR uses node / launch arguments to specify whether the driver should operate in "mock" mode, instead of using the sentinel name `Mock_spot`. With an explicit parameter, we can have multiple mocks, with different names, and also affect whether there is an arm.
For example, with this modification you can do
```
cd spot_driver
colcon build --symlink # (`symlink` [does not apply to launch files](https://github.com/colcon/colcon-core/issues/407))
source install/setup.bash
ros2 launch spot_driver spot_driver.launch.py spot_name:=AnyNameHere mock_enable:=True mock_has_arm:=True
```
and then, for example (`spot_utilities`, specifically in `bdai` repo)
```
cd spot_utilities # /workspaces/bdai/ws/src/spot_utilities
colcon build
source install/setup.bash
ros2 run spot_utilities spot_teleop.py …
```

[N/A] Add a mock launch argument

---

spot_driver/spot_driver/spot_ros2.py

Functionally equivalent (slightly different error message).

Clean up some frame checks

---

install_spot_ros2.sh

This PR bumps the version number of Spot C++ SDK install to 3.3.2 in the install script

[PN-112] Update install script with new Spot C++ SDK release

---

spot_driver/package.xml

We were missing the dependency on spot wrapper so a naive colcon build of spot driver would not build spot wrapper.

Add dependency on spot wrapper

---

.devcontainer/Dockerfile
README.md

Changes:
- Updated the release of spot-cpp-sdk used for CI to 3.3.2
- Updated the release of bosdyn_msgs used for CI to 3.3.2
- Updated README to say we correspond to 3.3.2

[N/A] Update docker for CI to use the 3.3.2 dependencies

---

spot_driver/package.xml

This PR fixes a small typo was introduced in the prior commit.

Fix typo in spot_driver package.xml

---

.pre-commit-config.yaml

Fixing issue https://github.com/bdaiinstitute/spot_ros2/issues/237 where mypy fails on pre-commit.  Tested by running pre-commit with additional dependency and mypy now passes.

Add protobuf to addional dependencies for mypy

---

spot_driver/spot_driver/spot_ros2.py

To support shared autonomy with multiple clients (e.g. `bosdyn.client.RobotCommandClient`), we need a way to ask `SpotROS` to take a new lease.
The underlying SpotWrapper exposes a `getLease` interface, which either takes or acquires the lease, depending on the configuration for the driver. This PR uses the underlying interface of SpotWrapper directly to expose a ROS service that takes the lease.
For example, a teleop agent may have taken control of Spot via `lease_client.take()`, and a skill commanding spot through `SpotROS` will need to ask `SpotROS` to generate a new lease when teleop is done in order to be able to control Spot again (because`SpotROS` would be running with `use_take_lease=True` and `get_lease_on_action=False`).

Add ROS service to take new Spot lease

---

README.md

Minor updates to README that includes how to install ROS 2.
N/A

[SW-657] Add ROS2 installation section to the README of Spot_Ros2

---

spot_driver/launch/spot_driver.launch.py

The goal of this PR is to check if the `config_file` launch argument for `spot_driver.launch.py` has been set, and if so, checks if it is a valid path. If this file is not valid, an exception is thrown. This happens before any nodes get launched so that there is no chance of partially launched "zombie nodes". 
I tested by running the spot driver with a physical Spot, passing in a nonexistent config file path. In this case the driver exits before any nodes get launched. If the config file was a real file, or if no config file was passed in (for example, if the user chooses to set parameters through environment variables instead) the behavior is unchanged. 
Example of the failure state:
```
$ ros2 launch spot_driver spot_driver.launch.py config_file:=notarealfile.yaml
[INFO] [launch]: All …
```

[SW-632] Check config file path exists in spot_ros2

---

spot_driver/launch/spot_driver.launch.py

This addresses [this issue](https://github.com/bdaiinstitute/spot_ros2/issues/247) of not being able to connect to Spot from `spot_driver.launch.py` without setting environment variables. Now, the spot driver can be launched with only a configuration file yaml (`config_file`) if the user chooses. 
The implementation parses the `config_file` yaml within the launchfile to determine if `username`,  `password`, and `hostname` are set there as ROS parameters. If both environment variables and `config_file` parameters are set, then the environment variables take priority (similar to the `get_from_env_and_fall_back_to_param` logic in `spot_ros2.py`).  It also assumes a yaml structure for `config_file` (if used) of the following:
```
/**:
ros__parameters:
username: ...
password: ...
hostname: …
```

[SW-679] Config. file is not used to get hostname, username, or password when running the driver

---

pull_request_template.md

This adds a basic PR template to `spot_ros2` (which was used to fill out this PR!). It is based off the template on our internal repositories. 
N/A

[SW-681] Add PR template to spot_ros2

---

spot_driver/test/CMakeLists.txt
spot_driver/test/src/test_clock_skew.cpp

Add test cases for `spot_ros2::applyClockSkew`.

Add tests for applying Spot clock skew to timestamps

---

spot_driver/include/spot_driver/interfaces/rclcpp_tf_interface.hpp
spot_driver/include/spot_driver/interfaces/tf_interface_base.hpp
spot_driver/src/interfaces/rclcpp_tf_interface.cpp
spot_driver/test/include/spot_driver/mock/mock_tf_interface.hpp

In practice, the rclcpp TF broadcaster cannot fail to send TF messages, so it's unnecessary to allow our TF broadcaster wrapper class to return an error result.

Make TfInterfaceBase::updateStaticTransforms return void instead of tl::expected

---

spot_driver/launch/spot_driver.launch.py

Current `spot_driver.launch.py` launchfile on main does not work, fails with
`executable 'kinematic_node' not found on the libexec directory`
and, when this was fixed,
`executable 'spot_robot_state_publisher_node' not found on the libexec directory`
These errors were introduced with #209 which implemented the robot state publisher in C++ and also changed the name of some nodes. This just updates to the correct node names.

[SW-794] hotfix for spot driver launchfile not launching

---

spot_driver/CMakeLists.txt
spot_driver/include/spot_driver/api/default_time_sync_api.hpp
spot_driver/include/spot_driver/api/time_sync_api.hpp
spot_driver/include/spot_driver/conversions/time.hpp
spot_driver/src/api/default_image_client.cpp
spot_driver/src/api/default_time_sync_api.cpp
spot_driver/src/conversions/robot_state.cpp
spot_driver/src/conversions/time.cpp
spot_driver/test/include/spot_driver/matchers.hpp
spot_driver/test/include/spot_driver/mock/mock_time_sync_api.hpp
spot_driver/test/src/test_clock_skew.cpp

- Rename functions for applying clock skew to timestamps to make their purpose clearer (from `applyClockSkew` to `localTimeToRobotTime`).
- Add `robotTimeToLocalTime` function to convert host-relative time to robot-relative time.
- Move functions related to converting timestamps into a new file.
- Remove unused `convertRobotTimeToLocalTime()` from time sync interface.
- This function combined retrieving the clock skew from Spot with applying it to a timestamp. In practice, we want to use a specific previously-retrieved clock skew instead of acquiring a new one, since the clock skew could change over time and we want to make sure it corresponds to the timestamp we're converting, so this function wasn't used.
These changes are needed for an in-development feature to synchronize TF frames …

[PN-134] Add function to convert host-relative time to robot-relative time

---

spot_driver/include/spot_driver/conversions/common_conversions.hpp
spot_driver/include/spot_driver/conversions/geometry.hpp
spot_driver/include/spot_driver/conversions/kinematic_conversions.hpp
spot_driver/src/api/default_image_client.cpp
spot_driver/src/conversions/common_conversions.cpp
spot_driver/src/conversions/geometry.cpp
spot_driver/src/conversions/kinematic_conversions.cpp
spot_driver/src/conversions/robot_state.cpp
spot_driver/src/kinematic/kinematic_service.cpp
spot_driver/test/src/conversions/test_common_conversions.cpp
spot_driver/test/src/conversions/test_geometry.cpp
spot_driver/test/src/conversions/test_kinematic_conversions.cpp

This changes the namespace of the `convertToRos` and `convertToProto` utility functions. Previously they were in specific namespaces depending on the type of messages they converted (e.g., `spot_ros2::kinematic_conversions::convertToRos`). A problem with this is that it requires the user to know all the namespaces in order to find a specific conversion function, which can result in developers inadvertently adding duplicate functions. After this change, they're all in the top-level `spot_ros2` namespace.
This also changes one input parameter to be passed by const reference instead of by const value. The parameter is `double` so there's no performance gain for avoiding the copy but it makes a warning in my IDE go away.
This also adds a parameterized test case for a message conversion that …

Move functions to convert between ROS and proto messages into top-level spot_ros2 namespace

---

.github/workflows/ci.yml

Follow-up to #256. It broke source paths in coverage reports. 
This patch amends the situation.

Fix Coveralls path

---

spot_driver/include/spot_driver/interfaces/parameter_interface_base.hpp
spot_driver/include/spot_driver/interfaces/rclcpp_parameter_interface.hpp
spot_driver/src/images/spot_image_publisher_node.cpp
spot_driver/src/interfaces/rclcpp_parameter_interface.cpp
spot_driver/src/kinematic/kinematic_node.cpp
spot_driver/src/robot_state/state_publisher_node.cpp
spot_driver/test/include/spot_driver/fake/fake_parameter_interface.hpp
spot_driver/test/src/images/test_spot_image_publisher.cpp
spot_driver/test/src/images/test_spot_image_publisher_node.cpp
spot_driver/test/src/test_parameter_interface.cpp

When launching the spot driver, there is logic to get the username, password, and spot IP address from an environment variable, and if they are not found, fall back to a ROS parameter. The `spot_ros2` node assumes that Spot's IP address, if specified in a config file, is listed as `hostname` whereas the `rclcpp_parameter_interface` in `spot_driver` assumes it is listed as `address`. This changes all instances of `address` to `hostname` to make launching with a config file fully functional and match the config file template given in [`spot_driver/config/spot_ros_example.yaml`](https://github.com/bdaiinstitute/spot_ros2/blob/main/spot_driver/config/spot_ros_example.yaml).

[SW-817] Unify login parameter names for launching driver from a config file

---

spot_driver/src/robot_state/state_publisher.cpp

Currently, if the spot driver is launched without a namespace, the odom frame will incorrectly be a child of the body frame. This is because there is some logic to set the full odom frame ID as `spot_name + "/" + preferred_odom_frame`.  
So with a namespace, this frame is `SpotName/odom`, and without a namespace it becomes `/odom` when it should be `odom` -- leading to some string comparison mismatches in `robot_state.cpp`. This PR makes the TF tree structure the same regardless of if there is a namespace or not. 
Relevant github issue: https://github.com/bdaiinstitute/spot_ros2/issues/302

[SW-859] Resolve TF errors with odom if driver is launched without a namespace

---

.coveragerc
.devcontainer/Dockerfile
.github/workflows/ci.yml
README.md
spot_driver/package.xml
spot_driver/test/CMakeLists.txt

- As the title says. Coverage should only be for packages from this repo.
- CI

[N/A] Update coverage report to ignore spot_wrapper & spot_examples

---

spot_driver/spot_driver/spot_ros2.py

`SpotWrapper` is not thread-safe, and thus reentrant ROS 2 callbacks risk resource contention. This patch synchronizes `SpotWrapper` use in general, and lease management in particular, by making all ROS 2 callbacks mutually exclusive.
It also makes use of https://github.com/bdaiinstitute/spot_wrapper/pull/92 to avoid reaching out to `SpotWrapper` internals.
In addition to green CI, I manually ran multiple examples on a real Spot (those in this repository and others in downstream repositories as well).

Synchronize Spot leasing

---

README.md

Tell users to ignore `proto2ros_tests` when building the repo in the README, and adds a "Help" section with common issues seen from the 3.3.2->4.0.0 upgrade. Open to other additions for the "Help" section. 
N/A

[N/A] update build instructions to ignore proto2ros_tests

---

spot_driver/spot_driver/spot_ros2.py
spot_driver/test/pytests/test_robot_command.py
spot_msgs/CMakeLists.txt
spot_msgs/srv/RobotCommand.srv

This patch adds a `RobotCommand` service, alongside the `RobotCommand` action, as a fire-and-forget interface in the Spot ROS 2 node.
~To be tested manually using teleop functionality.~ Tested through https://github.com/bdaiinstitute/bdai/pull/3211.

[EK-32] Add robot command service to Spot ROS 2

---

spot_driver/spot_driver/spot_ros2.py
spot_driver/test/pytests/test_ros_interfaces.py

Per the [4.0.0 release notes](https://dev.bostondynamics.com/docs/release_notes) there is a new enum in `ArmImpedanceFeedbackStatus` called `STATUS_TRAJECTORY_CANCELLED` (view details with `ros2 interface show bosdyn_api_msgs/msg/ArmImpedanceCommandFeedbackStatus`). If we receive a feedback message from a robot command with this status in `spot_ros2`, this will indicate that the Goal Response has failed.

[SW-735] Update spot_ros2 for the new ArmImpedanceCommandStatus enum

---

spot_driver/spot_driver/spot_ros2.py

Fixed typo in call to take lease function in driver

Hotfix - Typo in getting spot lease

---

spot_driver/include/spot_driver/api/default_image_client.hpp
spot_driver/include/spot_driver/api/default_kinematic_api.hpp
spot_driver/include/spot_driver/api/default_spot_api.hpp
spot_driver/include/spot_driver/api/default_state_client.hpp
spot_driver/include/spot_driver/api/default_time_sync_api.hpp
spot_driver/include/spot_driver/api/kinematic_api.hpp
spot_driver/include/spot_driver/api/spot_api.hpp
spot_driver/include/spot_driver/api/spot_image_sources.hpp
spot_driver/include/spot_driver/api/state_client_interface.hpp
spot_driver/include/spot_driver/api/time_sync_api.hpp
spot_driver/include/spot_driver/images/spot_image_publisher.hpp
spot_driver/include/spot_driver/interfaces/image_client_interface.hpp
spot_driver/include/spot_driver/interfaces/logger_interface_base.hpp
spot_driver/include/spot_driver/interfaces/node_interface_base.hpp
spot_driver/include/spot_driver/interfaces/parameter_interface_base.hpp
spot_driver/include/spot_driver/interfaces/rclcpp_node_interface.hpp
spot_driver/include/spot_driver/interfaces/rclcpp_parameter_interface.hpp
spot_driver/include/spot_driver/interfaces/tf_interface_base.hpp
spot_driver/include/spot_driver/interfaces/timer_interface_base.hpp
spot_driver/src/images/spot_image_publisher_node.cpp
spot_driver/test/src/images/test_spot_image_publisher.cpp

Fixes some things the clangd plugin in my IDE was complaining about:
- Mark member functions in derived classes which return values as being `[[nodiscard]]`. This helps enforce correct usage.
- Related: fix one place where a return value was being ignored.
- For the base interface classes, delete the copy constructor and explicitly define the default move constructor to indicate that these classes are move-only. This is primarily to enforce a particular pattern of usage, since it matches the way the implementations of these classes are used in the nodes.
- Fix minor doc typos and unused includes.
If the PR branch compiles and tests pass, then this is all set.

Explicitly define interface class copy and move constructors and mark functions as nodiscard

---

spot_driver/include/spot_driver/images/images_middleware_handle.hpp
spot_driver/include/spot_driver/images/spot_image_publisher.hpp
spot_driver/include/spot_driver/images/spot_image_publisher_node.hpp
spot_driver/src/images/images_middleware_handle.cpp
spot_driver/src/images/spot_image_publisher.cpp
spot_driver/src/images/spot_image_publisher_node.cpp
spot_driver/test/src/images/test_spot_image_publisher.cpp
spot_driver/test/src/images/test_spot_image_publisher_node.cpp

- Revise how `SpotImagePublisher::MiddlewareHandle` and `ImagesMiddlewareHandle` are implemented to move the interface classes out of the middleware handle and instead into `SpotImagePublisher`.
- This reduces the scope of the middleware handle, since now it's only responsible for publishing images instead of additionally being a container for unrelated functionality that's only used by `SpotImagePublisher`.
- Reduce code duplication in tests by using new test fixtures which were added after the original image publisher features.
- Remove some unused headers.
- (@jschornak-bdai's note: I haven't done this step yet)

Revise image publisher middleware handle to match pattern used by other driver nodes

---

spot_driver/spot_driver/spot_ros2.py

SpotWrapper's `graphnav` submodule has a `_navigate_to` function that was being mistaken for a `navigate_to` in `spot_ros2.py`. 
Proof:
https://github.com/bdaiinstitute/spot_wrapper/blob/bbca68b679212d78817e2834aeb9e2f0924b4e20/spot_wrapper/spot_graph_nav.py#L504
None. Potential to test on hardware.

[N/A] Fixed typo in the `navigate_to` function called by the graphnav

---

spot_examples/spot_examples/batch_trajectory.py

To execute an impedance trajectory you must comment out some lines 601 - 607. I added comments in the code to explain what is working, what is not working and how to run an impedance trajectory instead of a cartesian trajectory.

Impedance example for trajectory batching.

---

spot_driver/include/spot_driver/interfaces/rclcpp_tf_listener_interface.hpp
spot_driver/src/interfaces/rclcpp_tf_listener_interface.cpp

There is a noisy warning message from the TF buffer cautioning that `lookupTransform` should not be called with a timeout unless a separate thread is used to listen to TF data. We are indeed using a separate thread (since we require that RclcppTfListenerInterface be spun by a multithreaded executor) and we're not using the timeout duration when looking up transforms, so we can set that the buffer is using a separate thread to quiet this warning.
This also fixes an incorrect copyright year for a file added in #312.

Set that RclcppTfListenerInterface's TF buffer is using a separate thread to monitor TF data

---

spot_driver/src/images/spot_image_publisher.cpp

We assume the hand camera to always have rgb format, independent of the parameter "has_rgb_cameras"
We tested it on our spot, which has grayscale body cameras, tests on an rgb-spot would be required.
This PR is related to https://github.com/bdaiinstitute/spot_ros2/pull/193 and slightly adapts the simplified approach mentioned there.

Special handling of the hand camera format such that it always has RGB format

---

spot_driver/spot_driver/spot_ros2.py

Added services for `stow_arm`, `ready_arm`, and `carry` to `spot_ros2`
Ran the driver and tested the new services

[SW-940] Add arm stow, carry, and ready services to spot_ros2

---

spot_driver/spot_driver/spot_ros2.py

Added services `open_gripper` and `close_gripper` to `spot_ros2`

[SW-951] Add gripper open and close services to spot_ros2

---

spot_driver/include/spot_driver/api/default_spot_api.hpp
spot_driver/include/spot_driver/api/spot_api.hpp
spot_driver/include/spot_driver/interfaces/parameter_interface_base.hpp
spot_driver/include/spot_driver/interfaces/rclcpp_parameter_interface.hpp
spot_driver/launch/spot_driver.launch.py
spot_driver/package.xml
spot_driver/spot_driver/spot_ros2.py
spot_driver/src/api/default_spot_api.cpp
spot_driver/src/images/spot_image_publisher_node.cpp
spot_driver/src/interfaces/rclcpp_parameter_interface.cpp
spot_driver/src/kinematic/kinematic_node.cpp
spot_driver/src/object_sync/object_synchronizer_node.cpp
spot_driver/src/robot_state/state_publisher_node.cpp
spot_driver/test/include/spot_driver/fake/fake_parameter_interface.hpp
spot_driver/test/include/spot_driver/mock/mock_spot_api.hpp
spot_driver/test/pytests/conftest.py
spot_driver/test/pytests/test_robot_state.py
spot_driver/test/src/test_parameter_interface.cpp

Precisely what the title says. This patch restores tests after https://github.com/bdaiinstitute/spot_wrapper/pull/103 and opens the door to (`launch_`)`pytest` driven C++ integration tests, as both PRs combined effectively enable the Spot ROS 2 driver to run against a mock Spot over secure gRPC channels.

[SW-947] Add support for custom port and certificate

---

spot_driver/include/spot_driver/conversions/robot_state.hpp
spot_driver/src/conversions/robot_state.cpp
spot_driver/src/object_sync/object_synchronizer.cpp
spot_driver/test/CMakeLists.txt

The frame snapshot obtained when getting apriltag world objects from spot contains some static frames like the camera frames. This results in extreme spew from the driver about TF extrapolation to the future whenever an apriltag is in view which affects camera and point cloud publishing. (introduced in https://github.com/bdaiinstitute/spot_ros2/pull/312)
This solution filters out the frames in the world object TF broadcaster so that it only broadcasts the world object frames and doesn't rebroadcast the static frames. 
In working on this, I uncovered another issue with getting the list of current frames within the SyncWorldObjects function. The problem is the list of TF frames includes old TF frames that correspond to tags the robot can't see anymore (see: …

[SW-958] hotfix for TF spew from driver

---

spot_driver/launch/spot_driver.launch.py
spot_driver/spot_driver/spot_ros2.py

Added a service `spot_check` to run the spot check in `spot_ros2.py`
Ran the driver with no issues  
ran the `spot_check` service 

[SW-730] Add service in spot_ros2 to call spot check

---

spot_driver/src/images/spot_image_publisher_node.cpp

If the ImagesMiddlewareHandle is constructed using the node_options, it's creating it's own ros-node.
But when initialized from within SpotImagePublisherNode, the already existing ros-node must be used. Otherwhise it results in two ros-nodes with identical names and corresponding ROS2 warnings.
Compiles and runs now with only one /image_publisher node ;-)

Fix duplicated ros_node creation

---

spot_driver/spot_driver/spot_ros2.py

In the current version the driver calls the non existing method stow_arm which leads to a shutdown and subsequent crash.
In this pull request I changed it to the correct call of arm_stow wrapper function and unified the naming of the relevant arm services.

Fixed and unified the arm unstow, stow and carry services

---

spot_driver/spot_driver/spot_ros2.py

Precisely what the title says. If Spot is powered off before the driver is torn down, the driver will fail to sit.
Manually started the driver, powered off motors, stopped the driver.

Skip sit for shutdown Spot on driver node destruction

---

spot_driver/include/spot_driver/images/images_middleware_handle.hpp
spot_driver/include/spot_driver/images/spot_image_publisher.hpp
spot_driver/src/images/images_middleware_handle.cpp
spot_driver/src/images/spot_image_publisher.cpp
spot_driver/test/src/images/test_spot_image_publisher.cpp
spot_driver/test/src/images/test_spot_image_publisher_node.cpp

By sending both, the compressed image and the image within same function.
unit test run
image transport rotation nodes used for rotating the frontcameras for Rviz don't complain (too often) on mismatches between image and camera_info topics.

Prevent from duplicated camera_info msgs

---

spot_driver/spot_driver/spot_ros2.py
spot_driver/test/pytests/test_clear_behavior_fault.py

Precisely what the title says. The `clear_behavior_fault` service implementation has been broken since https://github.com/bdaiinstitute/spot_ros2/commit/0b2ba6fd824012a2a0d37798b696ef00b0d6bdeb. `SpotWrapper.clear_behavior_fault` has always returned a triplet (https://github.com/bdaiinstitute/spot_wrapper/commit/c58154b863111645ffa5e039acc7695be6e1b5d4).

Fix `/clear_behavior_fault` service

---

install_spot_ros2.sh

Resolves https://github.com/bdaiinstitute/spot_ros2/issues/381. Now no user input is needed during the portion of the install script that installs `bosdyn_msgs`. 
I needed the `--nox11` flag as when piping in the `yes`, as by default this opens another terminal session that doesn't register anything before the pipe.

[N/A] make install script fully automatic

---

README.md
spot_driver/CMakeLists.txt
spot_driver/config/spot_ros_example.yaml
spot_driver/include/spot_driver/image_stitcher/image_stitcher.hpp
spot_driver/include/spot_driver/image_stitcher/image_stitcher_node.hpp
spot_driver/launch/spot_driver.launch.py
spot_driver/package.xml
spot_driver/src/image_stitcher/image_stitcher.cpp
spot_driver/src/image_stitcher/image_stitcher_node.cpp
spot_driver/src/image_stitcher/image_stitcher_node_main.cpp

Adds `image_stitcher_node` to `spot_driver` to stitch together the front camera images and publish the stitched image and the transform to the virtual camera.
This node can get launched now when running `spot_driver.launch.py` with the launch argument `stitch_front_images:=True` (it is disabled by default). Default parameters for the image stitcher node have also been added to the example `spot_ros_example.yaml` configuration file.   Users will need to update their configuration files with these values in order to receive any meaningful stitched images as we do not launch the driver with a default configuration file. 
On robot testing was successfully able to view the stitched image:
The stitched image comes in at around 1/2 the speed as the standard camera streams on my system. If this …

[PN-60] Add node to stitch front camera images

---

README.md
spot_driver/launch/spot_driver.launch.py
spot_driver/launch/spot_image_publishers.launch.py
spot_driver/spot_driver/launch/spot_launch_helpers.py

We used to have a standalone image publisher launchfile for the python image publishers, this adds an equivalent for C++:
```
ros2 launch spot_driver spot_image_publishers.launch.py
```
This new image publisher launchfile gets called from within the main driver launchfile so that the main driver interface stays the same. Additionally, there is a new launch argument in the driver that allows you to completely turn off image publishing (`launch_image_publishers:=False`).
This also adds a file `spot_launch_helpers` with some common pure python functions that are shared between the two launchfiles (right now, just to query if Spot has an arm or not). 
* rgb images
* depth images
* depth registered images
* point clouds
* stitched images
* compressed images

[SW-1091] Make a standalone image publisher launchfile

---

README.md
install_spot_ros2.sh

Updates this repo for spot-sdk 4.0.2!

[SW-1112] update install_spot_ros2.sh for SDK 4.0.2

---

spot_driver/config/spot_ros_example.yaml
spot_driver/launch/spot_driver.launch.py
spot_driver/spot_driver/spot_ros2.py

There were a few parameters in `spot_ros_example.yaml` that are declared but completely unused. Given that we direct people to this as an example, I wanted to clean this up so that only relevant parameters remain. 
Additionally, this removes the image publishers from the main python `spot_ros2` node as they have been unused for a long time and were related to some of the parameters that were unused. 
The other config files also seem to be unmaintained but opted not to delete them as they might be used by some people? (planar.yaml, teleop.yaml, twist_mux.yaml)

[SW-1121] Parameter cleanup in example yaml and spot_ros2 node

---

spot_driver/spot_driver/spot_ros2.py

Currently, when you CTRL+C the driver, Spot will sit. If the estop is held by the tablet, this is annoying to deal with if you are starting and stopping the driver often, so this PR removes this feature.
If the estop is held by the driver, we still need to force sitting on shutdown, otherwise the robot will collapse to the ground if you CTRL+C.
EDIT: https://github.com/bdaiinstitute/spot_wrapper/pull/122 and https://github.com/bdaiinstitute/spot_ros2/pull/420 need to go in first so I can use the blocking version of the sit command.

[SW-736] Only sit on shutdown if driver holds the estop

---

spot_driver/package.xml

Precisely what the title says. This omission is causing CI failures.
I'll leave this to CI.

Add `python3-tk` as `spot_driver` dep

---

README.md
spot_driver/config/spot_ros_example.yaml
spot_driver/include/spot_driver/api/spot_image_sources.hpp
spot_driver/include/spot_driver/interfaces/parameter_interface_base.hpp
spot_driver/include/spot_driver/interfaces/rclcpp_parameter_interface.hpp
spot_driver/include/spot_driver/types.hpp
spot_driver/launch/spot_image_publishers.launch.py
spot_driver/spot_driver/launch/spot_launch_helpers.py
spot_driver/src/api/spot_image_sources.cpp
spot_driver/src/images/spot_image_publisher.cpp
spot_driver/src/interfaces/rclcpp_parameter_interface.cpp
spot_driver/test/include/spot_driver/fake/fake_parameter_interface.hpp
spot_driver/test/src/images/test_spot_image_sources.cpp
spot_driver/test/src/test_parameter_interface.cpp

Allows the user to specify the cameras they want to stream from in their config file. This can help alleviate some bandwidth problems from streaming from all cameras all the time. 
For example, to only stream from the frontleft, frontright, and hand cameras, you can add the following to the config yaml:
```
cameras_used: ["frontleft", "frontright", "hand"]
```

[SW-1142] Add cameras_used parameter

---

spot_driver/spot_driver/spot_ros2.py

Precisely what the title says. The `ExecuteDance` action server implementation has other problems when action leaves the happy path, but for the time being this patch completes the happy path.
Manually at the Spot lab.

[N/A] Mark successful `ExecuteDance` goals as successful

---

spot_driver/spot_driver/spot_ros2.py

with only lower max_vel set, spot still travels at full speed
this fixes it
also, these limits do not affect cmd_vel (velocity) commands
Please include a summary of the changes made and the relevant ticket or issue.

set minimum velocity as well when setting velocity limits

---

Dockerfile
README.md

I had spoken with @khughes-bdai on a previous Issue's discussion about creating a dockerfile that can be used to run the driver in production (whether that be on a computer or pushing it to Spot CORE I/O). This is separate from the Dockerfile found in the .devcontainer directory, as that is for creating a containerized development environment for something like GitHub Codespaces.
This PR adds a dockerfile to the root of the repository that can be used to run driver within a docker container. It uses the `osrf/ros-noetic-desktop-full` image as a base, and automatically downloads and installs the driver code from this repository.
I've pushed the built image to my docker hub account for convenience. It can be found at `ryroche/spot_ros2`
This PR is a bit abnormal, as it does not modify any …

Added dockerfile for running the driver

---

spot_driver/include/spot_driver/image_stitcher/image_stitcher.hpp
spot_driver/launch/spot_image_publishers.launch.py
spot_driver/src/image_stitcher/image_stitcher.cpp

The stitched image published currently is missing relevant info in its header (time stamp and frame ID). Additionally, the camera info topic for the stitched image was not remapped correctly, so the image and camera info topics had different names. This resolves both of these issues.

[SW-1252] add missing header for stitched image, and correctly remap stitched image camera info topic from launchfile

---

spot_driver/spot_driver/spot_ros2.py

Was causing CI issues on internal repo as it is not a valid input to SpotCamWrapper

[N/A] remove gripperless param from SpotCamWrapper

---

spot_driver/spot_driver/spot_ros2.py

Get/set gripper camera parameters and override grasp or carry should get created as services if the robot is not gripperless
Also removes the cameras_used param in spot_ros2.py as it isn't used in the Python version of the driver

[N/A] Services correctly created if not gripperless 

---

spot_driver/spot_driver/spot_ros2.py
spot_driver/test/pytests/test_ros_interfaces.py

When the robot rolls over to battery change pose, it powers off automatically. That can result in the otherwise successful battery change pose command to be overridden. This patch is a best-effort approach to try and cope with this. It is a workaround, as there is currently no way to unequivocally differentiate a true override from an incidental one.
On real hardware, downstream.

[N/A] Workaround automatic power off on rollover

---

spot_description/launch/description.launch.py
spot_description/urdf/spot.urdf.xacro
spot_description/urdf/spot_feet_macro.urdf
spot_description/urdf/spot_macro.xacro

This now lets you generate a URDF of spot that puts links at the feet locations. It is possible to visualize this with `ros2 launch spot_description description.launch.py feet:=true`. 
The default URDF that gets generated for running the driver does not include these new frames.

[SW-1266] Add option in spot urdf to put links at the feet

---

spot_ros2_control/README.md
spot_ros2_control/launch/noarm_squat.launch.py
spot_ros2_control/launch/spot_ros2_control.launch.py
spot_ros2_control/launch/wiggle_arm.launch.py
spot_ros2_control/package.xml
spot_ros2_control/xacro/spot.ros2_control.xacro

* when connected to a robot, the launchfile will auto determine if the robot has an arm and use that to generate the URDF that gets used by the hardware interface (same as in `spot_driver`)
* default controller config file that gets loaded is also now auto determined from if the robot has an arm. 
* This required some reworking of the core launchfile to use an opaque function to add this extra logic
* Allows users to specify login info for the robot in a configuration yaml file, same as spot driver.
* Introduces a dependency on `spot_driver` so that the launchfile can use this code in `spot_driver.launch.spot_launch_helpers`. This could be reworked in the future if we decide we don't want these packages so coupled.
* minor changes to launch arguments to make the user interface simpler and …

[SW-1316] ros2 control: auto determine if robot has an arm in launchfile

---

README.md
spot_driver/CMakeLists.txt
spot_driver/spot_driver/calibrated_reregistered_hand_camera_depth_publisher.py

This allows Spot to use a calibration to register the depth image to the rgb frame
in the hand
[SW-1245] This builds on capability created in https://github.com/bdaiinstitute/spot_wrapper/pull/131#issue-2473965414
(This allows Spot to automatically calibrate the hand cameras, coming up with a stereo pair correspondence for the ToF and RGB cameras.)
Tested the calibration sequence on a few different spots, varying the calibration parameters. Conducted drop in tests with ROS 2 bags (see below), as well as just testing running the publisher alongside all other other nodes. Verified that republished depth image creates a Point Cloud is in the same frame and orientation as the default depth image.
Recording relevant topics
```
ROBOT_NAME=ROBOT_NAME
ros2 bag record --output drop_in_test …
```

[SW-1245] : Custom Gripper Calibration Result Republisher

---

spot_description/urdf/spot_arm_macro.urdf
spot_description/urdf/spot_macro.xacro

Updates velocity limits in URDF following this response from BD support:
"Regarding the maximum velocity limits, unfortunately we do not have any hard numbers on this. For the hip joints we use an internal value of 900/51 rad/s as a limit for jointspace planning. The knee is more complex due to the variable transmission, but an average value of 900/75 rad/s is a reasonable value. For the arm we use a value of 10 rad/s for jointspace planning. Note: these are not no-load speeds, but software limits."
N/A

[N/A] update velocity limits in URDF with more accurate values

---

spot_ros2_control/CMakeLists.txt
spot_ros2_control/examples/src/joint_command_passthrough.cpp
spot_ros2_control/hardware/include/spot_ros2_control/spot_joint_map.hpp

Node for Maple Action Stack integration:
`joint_command_passthrough` is a node that listens to `joint_states` and saves all the current states, but then pass through any new `/joint_commands` received to the `forward_position_controller`
Will test on robot in the morning

Joint Passthrough node for Action Stack Integration

---

spot_driver/CMakeLists.txt

- If ccache is installed now it can be used to speed up rebuilds of the spot_driver
- Built the driver (plus this is standard)

Add the ability to use ccache

---

spot_driver/spot_driver/spot_ros2.py

Adds a subscriber to `spot_ros2` to accept `JointState` messages on the `/arm_joint_commands` topic to execute (as fast as possible)
Goes along with https://github.com/bdaiinstitute/spot_wrapper/pull/139
Tested with the Maple `action_stack_spot` package sending joint trajectories

Add simple JointState msg support

---

spot_driver/spot_driver/spot_ros2.py
spot_msgs/CMakeLists.txt
spot_msgs/srv/SetGripperAngle.srv

This adds a service `<spot_name>/set_gripper_angle` that allows us to do more than just open and close the gripper and instead set a desired joint angle for the `f1x` joint.
As a side while I was here, I also moved the previously added `/arm_joint_commands` subscription to only appear when the robot has an arm
Tested on robot running maple's Action Stack

[MAPLE-663] Spot Gripper Angle Service

---

spot_driver/src/image_stitcher/image_stitcher.cpp

Image stitcher currently crashes if run on a spot with greyscale cameras, this should resolve that error.
See: https://github.com/bdaiinstitute/spot_ros2/issues/448

[SW-1465] Fix image stitching for greyscale images

---

.devcontainer/Dockerfile
.github/workflows/ci.yml
README.md
install_spot_ros2.sh
pyproject.toml
spot_driver/CMakeLists.txt
spot_driver/package.xml
spot_ros2_control/CMakeLists.txt
spot_ros2_control/hardware/src/spot_hardware_interface.cpp
spot_ros2_control/package.xml

Precisely what the title says. This patch updates both C++ and Python SDKs, as well as `bosdyn_msgs`  for ROS 2 integration.
Relying on CI and downstream tests.

Bump Spot SDK from `4.0.2` to `4.1.0`

---

spot_description/urdf/spot.ros2_control.xacro
spot_description/urdf/spot.urdf.xacro
spot_hardware_interface/include/spot_hardware_interface/spot_constants.hpp
spot_hardware_interface/include/spot_hardware_interface/spot_hardware_interface.hpp
spot_hardware_interface/src/spot_hardware_interface.cpp
spot_ros2_control/README.md
spot_ros2_control/launch/spot_ros2_control.launch.py

1. standardizes gain names in the hardware interface to `k_q_p` and `k_qd_p`, same as spot sdk (https://dev.bostondynamics.com/docs/concepts/joint_control/readme)
2. allows taking in `k_q_p` and `k_qd_p` through a a parameter file. If you have a yaml that looks like this
```
/**:
ros__parameters:
k_q_p: [624.0, 936.0, 286.0,  624.0, 936.0, 286.0, 624.0, 936.0, 286.0, 624.0, 936.0, 286.0, 1020.0, 255.0, 204.0, 102.0, 102.0, 102.0, 16.0]
k_qd_p: [5.20, 5.20, 2.04, 5.20, 5.20, 2.04, 5.20, 5.20, 2.04, 5.20, 5.20, 2.04, 10.2, 15.3, 10.2, 2.04, 2.04, 2.04, 0.32]
```
and pass it to the `spot_ros2_control.launch.py` launchfile with the arg `config_file:=<file path>`, these gains will get used in the hardware interface to stream commands.
[Because ros2 control hardware interfaces don't have "true" …

[SW-1466] ability to take joint gains in through a parameter file

---

spot_driver/include/spot_driver/interfaces/parameter_interface_base.hpp
spot_driver/include/spot_driver/interfaces/rclcpp_parameter_interface.hpp
spot_driver/spot_driver/launch/spot_launch_helpers.py
spot_driver/src/images/spot_image_publisher.cpp
spot_driver/src/interfaces/rclcpp_parameter_interface.cpp
spot_driver/test/include/spot_driver/fake/fake_parameter_interface.hpp
spot_driver/test/src/test_parameter_interface.cpp

The `gripperless` parameter was added recently to the python spot_ros2.py node . This also adds support for the same parameter in the C++ nodes, namely the image publishing stack so it doesn't try to request images from the hand camera if the robot is gripperless.

[SW-1539] don't publish images from hand camera if gripperless param set

---

spot_description/launch/description.launch.py
spot_description/urdf/spot.urdf.xacro
spot_description/urdf/spot_arm_macro.urdf
spot_description/urdf/spot_macro.xacro

Adds support for the `gripperless` parameter at the URDF level, with the option to connect a new child link to joint `arm_wr1` (which would be the case when using a custom gripper)
related to https://github.com/bdaiinstitute/spot_ros2/pull/518
```
<?xml version="1.0" ?>
<robot name="gripperless_test" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find spot_description)/urdf/spot_macro.xacro" />
<xacro:load_spot
arm="true"
gripperless="true"
tf_prefix=""
custom_gripper_base_link="gripper_base_link"/>
<link name="gripper_base_link" />
</robot>
```

[SW-1507] gripperless URDF for Spot

---

spot_description/urdf/spot_arm_macro.urdf

fixes an issue where new gripperless arguments needed to be specified for loading the arm URDF. now if they aren't specified, defaults are used instead of throwing an error.

[N/A] bugfix: give new xacro arguments default values

---

spot_driver/launch/spot_driver.launch.py

This allows you to change the pack from where to get the robot description. This allows us to have different configurations of the robot (such as custom payloads)
Makes the (hard) assumption that whatever package you point it to has `{package}/urdf/spot.urdf.xacro` in it.
@tcappellari-bdai @khughes-bdai feel free to agree/disagree with this, but only way I could get extra collision objects in as needed on hardware

[MAPLE-681] Add robot_description_package as parameter to driver launch

---

spot_driver/spot_driver/launch/spot_launch_helpers.py
spot_driver/spot_driver/spot_ros2.py

Having recently gotten access to a gripperless spot, I discovered some bugs that came from not correctly passing the gripperless parameter to SpotWrapper (this resulted in the robot trying to access gripper related servers and hanging).

[N/a] fix for launching the driver without the gripper

---

spot_driver/config/spot_ros_example.yaml
spot_driver/include/spot_driver/interfaces/parameter_interface_base.hpp
spot_driver/include/spot_driver/interfaces/rclcpp_parameter_interface.hpp
spot_driver/include/spot_driver/robot_state/state_publisher.hpp
spot_driver/spot_driver/spot_ros2.py
spot_driver/src/conversions/robot_state.cpp
spot_driver/src/interfaces/rclcpp_parameter_interface.cpp
spot_driver/src/object_sync/object_synchronizer.cpp
spot_driver/src/robot_state/state_publisher.cpp
spot_driver/test/include/spot_driver/fake/fake_parameter_interface.hpp
spot_driver/test/src/test_parameter_interface.cpp

The goal of this PR is to allow the body frame to be the root of the tf tree, in case you want to broadcast your own custom odometry transform to "body". Currently that's not possible as body always has either odom or vision as a parent, and a tf frame cannot have more than two parents. 
* adds new parameter `tf_root` to allow you to specify what frame will be the root of the TF tree. 
* If unset it will default to "odom", which is the current behavior on main
* you can set `tf_root` to "vision" or "body" and pass this in via config file, and those frames will become the TF root as expected. (All the other frames and transforms still exist, it just changes the layout of the tree). 
* Nothing about the odometry topic parent frame changes as the expectation is this should be handled by the …

[SW-1658] Allow body frame to be root of TF tree

---

spot_driver/include/spot_driver/conversions/robot_state.hpp
spot_driver/launch/spot_driver.launch.py
spot_driver/src/conversions/robot_state.cpp
spot_driver/src/robot_state/state_publisher.cpp
spot_driver/test/include/spot_driver/robot_state_test_tools.hpp
spot_driver/test/src/conversions/test_robot_state.cpp

The `preferred_odom_frame` parameter is supposed to let you chose whether "odom" (default) or "vision" frame is used as the base frame in the `/odometry` topic. On main right now this is hardcoded to "odom" in the launchfile
This PR allows you to actually change this parameter. It also introduces some logic to deal with getting the velocity of the body in either the "odom" or "vision" frame, depending on which choice is selected. There is also some minor launchfile cleanup here. 
related to: https://github.com/bdaiinstitute/spot_ros2/issues/29, and takes a lot of work from https://github.com/bdaiinstitute/spot_ros2/pull/416

[SW-1764] allow use of preferred_odom_frame parameter

---

spot_driver/src/api/default_time_sync_api.cpp
spot_driver/src/image_stitcher/image_stitcher.cpp

The DefaultTimeSyncApi is missing the `WaitForSync` call from Spot SDK. As a result the timesync cannot be established, especially when connecting via WIFI.
I added the  `WaitForSync` call to the DefaultTimeSyncApi with a timeout of 5 seconds (maybe create a config param for that) before checking the timesync with `HasEstablishedTimeSync`
This results in a successful timesync even via WIFI over VPNs. 
Corresponding issue:
https://github.com/bdaiinstitute/spot_ros2/issues/527
1. Launched the driver with various parameters
2. Tested the image services
3. Tested robot commands such as dock and undock

Fixes TimeSync with robot

---

.github/workflows/ci.yml
.github/workflows/maintenance.yml

This is simply a find/replace of `ubuntu-latest` -> `ubuntu-22.04`.  Because `ubuntu-latest` will become 24.04 soon.  We should pin to 22.04 which matches our development environment.
None. This PR is the test.  (Assuming this repo has CI)

[SW-1712] Pin ubuntu version in workflows

---

spot_hardware_interface/src/spot_hardware_interface.cpp

This came up recently when running the ros2 control stack on a robot that had an expired joint level control license. The error message spammed in this state is just "Failed to get robot state" which is not very helpful. Now this tells the user to double check for the license. 
N/A

[N/A] better error message if robot is missing joint level api license

---

spot_driver/launch/point_cloud_xyz.launch.py
spot_driver/launch/point_cloud_xyzrgb.launch.py
spot_driver/launch/rviz.launch.py
spot_driver/launch/spot_driver.launch.py
spot_driver/launch/spot_image_publishers.launch.py
spot_ros2_control/launch/spot_ros2_control.launch.py

Reverts the calls to `update_sigterm_sigkill_timeout` introduced in https://github.com/bdaiinstitute/spot_ros2/pull/537. I have a very strong hunch that this is tanking CI execution time in our internal repo (after this change, we are only able to complete 17% of relevant tests before timing out, which is blocking my PR to bring in the latest changes from this repo).
N/A

[N/A] revert update_sigterm_sigkill_timeouts

---

spot_driver/spot_driver/spot_ros2.py

Adding in a service to crouch (stand at the lowest height possible) Spot. This is needed to increase the reachable space closer to the ground :)

[N/A] Add crouching stand service

---

spot_hardware_interface/src/spot_hardware_interface.cpp
spot_ros2_control/README.md
spot_ros2_control/config/spot_default_controllers_with_arm.yaml
spot_ros2_control/config/spot_default_controllers_without_arm.yaml
spot_ros2_control/launch/spot_ros2_control.launch.py

Safe concurrent use of `spot_ros2_control` and `spot_driver` will require cooperation and coordination. This patch is a step towards both around leases. `spot_ros2_control` should not forcibly take leases, only a human should (e.g. using the Spot tablet), nor should it attempt to acquire a lease unless instructed to. 
`spot_ros2_control` demos tested on Opal (thanks @khughes-bdai !)

[SW-1891] Make Spot hardware interface polite around leases 

---

.devcontainer/Dockerfile
README.md
install_spot_ros2.sh

Precisely what the title says. 
Manually tested several examples, available here and downstream, on Opal. At least that were safe to run in a tight spot. I'll run a few more early next week but all seems to indicate this patch is safe to go.
Edit: all examples tested on Nyla. Looks about right.

Bump Spot SDK version from 4.1.0 to 4.1.1

---

spot_hardware_interface/include/spot_hardware_interface/spot_hardware_interface.hpp
spot_hardware_interface/src/spot_hardware_interface.cpp
spot_ros2_control/config/spot_default_controllers_with_arm.yaml
spot_ros2_control/config/spot_default_controllers_without_arm.yaml
spot_ros2_control/launch/spot_ros2_control.launch.py

Follow-up to #567. This patch:
- loads hardware interfaces unconfigured
- ensures user-defined port and SSL certificate are picked up
- allows `spot_ros2_control` to be launched on its own (no `rviz`, no `robot_state_publisher`, etc.)
Integration tests, downstream. Local tests to ensure there have been no regressions are pending.

[SW-1891] Complete `spot_ros2_control` initialization

---

spot_driver/spot_driver/ros_helpers.py
spot_driver/spot_driver/spot_ros2.py

Made a descriptor class for trigger services to reduce boilerplate + copy/paste code in trigger service handlers
Tested all trigger services on robot. Found a bug with estop handling within `spot_wrapper` (will make a new ticket to track this but out of scope for this PR)

[SW-957] make decorator for trigger services

---

spot_driver/spot_driver/spot_ros2.py

Just changed some logic inside of `handle_trajectory()` member function to properly handle the new flags/logic created in the corresponding `spot_wrapper` branch. Going to keep this as a draft until the corresponding branch in `spot_wrapper` is merged to main.
Depends on https://github.com/bdaiinstitute/spot_wrapper/pull/156
Tested on Rex in spot lab. Confirmed that it will report "Trajectory complete: failed to reach goal" if it is unable to reach the goal. Previously, it would instead say "Reached goal" and success. Trajectory duration time out fail also tested and still sends proper feedback and result.

Fix false trajectory success when blocked by obstacle

---

spot_hardware_interface/include/spot_hardware_interface/spot_constants.hpp
spot_hardware_interface/include/spot_hardware_interface/spot_hardware_interface.hpp
spot_hardware_interface/src/spot_hardware_interface.cpp

Adds k_q_p and k_qd_p to the command interface of Spot's hardware interface.These get set to an initial value via the `initial_value` field from the URDF, so existing logic here in the hardware interface to parse this input has been removed in favor of this new method. Existing controllers will not need to change anything, as they simply don't claim the interface. 
The following PR in the stack will set up a controller to allow users to easily change this at runtime.
This PR also depends on the changes from https://github.com/bdaiinstitute/spot_description/pull/3 to expose these new command interfaces in the URDF. 
The default behavior from the user interface does not change with this PR.
\\

[SW-2049] ability to stream joint gains through hardware interface

---

spot_driver/launch/spot_driver.launch.py
spot_ros2_control/launch/spot_ros2_control.launch.py

The robot state publisher defaults to a TF update rate of 20 Hz, this needs to be increased to prevent slow TF lookups :) 
* spot driver publishes joint states at 50 Hz, so its TF update rate should be at least that
* spot ros2 control publishes joint states at 333 Hz, so its TF update rate should be at least that

[SW-2000] increase robot state publisher rates for faster tf lookups

---

spot_hardware_interface/CMakeLists.txt
spot_hardware_interface/include/spot_hardware_interface/spot_hardware_interface.hpp
spot_hardware_interface/include/spot_hardware_interface/spot_leasing_interface.hpp
spot_hardware_interface/package.xml
spot_hardware_interface/src/spot_hardware_interface.cpp
spot_hardware_interface/src/spot_leasing_interface.cpp

This PR modifies `spot_hardware_interface` to support leasing Spot through a `lease_manager` node (aka the proxy). Needs https://github.com/bdaiinstitute/spot_description/pull/2.
TBD

[SW-1999] Add support for Spot leasing by proxy to its hardware interface

---

spot_driver/spot_driver/spot_ros2.py

Found out this service was accidentally removed in https://github.com/bdaiinstitute/spot_ros2/pull/578, breaking some CI tests we have internally, this adds it back so we can sync the latest hash
N/A

[N/A] hotfix: bring back set gripper camera parameters service

---

install_spot_ros2.sh

Noticed when running code locally that my `colcon build`s were failing because I was missing the bondcpp dependency added recently. This adds it to the install script
Ran script locally

Add bondcpp dependency to install_spot_ros2.sh

---

spot_hardware_interface/include/spot_hardware_interface/spot_hardware_interface.hpp
spot_hardware_interface/src/spot_hardware_interface.cpp
spot_ros2_control/config/spot_default_controllers_with_arm.yaml
spot_ros2_control/config/spot_default_controllers_without_arm.yaml

expose foot contact states in state streaming handler

[SW-2051] expose foot contact states to state streaming handler

---

install_spot_ros2.sh

Though `bondcpp` has been added, `bondpy` dependency is required in spot_driver to start it. 
Tested with Docker on arm. 
https://github.com/bdaiinstitute/spot_ros2/issues/612

Fixes missing bondpy dependency

---

.github/workflows/ci.yml
install_spot_ros2.sh
spot_ros2_control/package.xml

Just a small thing. I refactored the ROS dependency installation steps in `install_spot_ros2.sh` to use the `rosdep` utility instead of having to add the manual install commands. I made an assumption that `rosdep` might not be installed on the machine at all, so it will also attempt to install and initialize.
There were 3 packages that are not included in any `package.xml` definitions:
* `tf_transformations`
* `ros2_control`
* `ros2_controllers`
All spot packages are building locally on my machine and the driver launches without having these three installed, so I didn't proactively include them anywhere. However, we don't have the joint-level API license, so I don't think I'll be able to test if any of the `spot_ros2_control` nodes don't need some of those libraries at runtime.
Unrelated: …

Use `rosdep` to install ROS 2 dependencies

---

spot_driver/spot_driver/spot_ros2.py

This is was #611 but I couldn't sort the sign-off stuff
Testing was done on https://app.graphite.dev/github/pr/bdaiinstitute/bdai/13356/%5BSW-1642%5D-Update-Spot-grasp-planning-to-take-advantage-of-correct-returns-from-spot-ros2

[SW-1642] spot driver should interpret grasp planning succeeded as success when request was only for planning

---

spot_hardware_interface/include/spot_hardware_interface/spot_hardware_interface.hpp
spot_hardware_interface/src/spot_hardware_interface.cpp

Exposes the odom to body and vision to body transforms in the ros2_control hardware interface.
Needs https://github.com/bdaiinstitute/spot_description/pull/10

[Sw-2050] expose body pose

---

.github/CODEOWNERS
.github/workflows/ci.yml
spot_controllers/CMakeLists.txt
spot_controllers/package.xml
spot_hardware_interface/CMakeLists.txt
spot_hardware_interface/package.xml
spot_ros2_control/CMakeLists.txt
spot_ros2_control/package.xml
spot_ros2_control/test/CMakeLists.txt
spot_ros2_control/test/pytests/conftest.py
spot_ros2_control/test/pytests/test_spot_ros2_control.py

Adds a simple CI test for `spot_ros2_control`. The main goal of having this test is to ensure that the `spot_ros2_control` launchfile can launch without error. For example, updates to `spot_description` have broken this in the past, but we had no way of seeing this through CI. This test also verifies that joint states from the Spot SDK are passed to the joint state broadcaster correctly using the `MockSpot` testing fixture. In the future we can add more tests to verify our Spot specific controllers/broadcasters in CI.
Additionally, i removed the `ament_lint_auto` and `ament_lint_common` test dependencies from `spot_hardware_interface` and `spot_controllers` as we are not running these linters in our other core packages (i.e. `spot_driver`) -- this makes the entire repo pass `colcon test` …

[SW-2321] Simple CI test for spot ros2 control

---

spot_controllers/CMakeLists.txt
spot_controllers/README.md
spot_controllers/include/spot_controllers/spot_pose_broadcaster.hpp
spot_controllers/include/spot_controllers/spot_pose_broadcaster_parameters.yaml
spot_controllers/spot_controllers.xml
spot_controllers/src/spot_pose_broadcaster.cpp
spot_ros2_control/README.md
spot_ros2_control/launch/spot_ros2_control.launch.py

Adds a `spot_pose_broadcaster` controller plugin that exposes the low level `odom_t_body` and `vision_t_body` poses.
New TF frames: they are the same as `<spot name>/odom` and `<spot name>/vision`, respectively, but obtained through the joint level API and are broadcasted at 333 Hz
* `<spot_name>/low_level/odom`
*  `<spot_name>/low_level/vision`
New published topics, which contain the same transforms but in ROS Pose msg form:
* `/<spot name>/spot_pose_broadcaster/odom_t_body`
* `/<spot name>/spot_pose_broadcaster/vision_t_body`
largely based off of https://github.com/ros-controls/ros2_controllers/tree/humble/pose_broadcaster
[Screencast from 05-01-2025 12:59:18 PM.webm <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" …

[SW-2328] ROS 2 control pose broadcaster

---

spot_hardware_interface/CMakeLists.txt

spot_hardware_interface fails to build due to missing tl_expected header.
Adding `tl_expected` to list of package include dependencies fixes the build error.
Tested on ubuntu 22.04, outside of docker, with all dependencies installed as specified by readme. Built with 
`colcon build --packages-up-to spot_ros2_control`

added missing tl_expected dependency

---

.devcontainer/Dockerfile
README.md
install_spot_ros2.sh
spot_driver/src/conversions/robot_state.cpp
spot_driver/test/include/spot_driver/matchers.hpp
spot_driver/test/include/spot_driver/robot_state_test_tools.hpp
spot_driver/test/src/conversions/test_robot_state.cpp
spot_msgs/msg/SystemFault.msg

Updates from spot sdk 4.1.1 to 5.0.0.
* Needs: https://github.com/bdaiinstitute/spot_wrapper/pull/167
* Uses release of spot-cpp-sdk here: https://github.com/bdaiinstitute/spot-cpp-sdk/releases/tag/v5.0.0
* Uses release of bosdyn_msgs here: https://github.com/bdaiinstitute/bosdyn_msgs/releases/tag/5.0.0
There were two deprecation warnings that came up during testing. First, `uid` in the System Fault proto was deprecated in favor of `uuid` [here](https://github.com/bdaiinstitute/spot-cpp-sdk/blob/6d8255c3165741ba0b398e6c72010fb3251b2f6b/protos/bosdyn/api/robot_state.proto#L265). This has been updated in this PR as this is a minor change.
Second, `end_effector_force_in_hand` has been deprecated in favor of `end_effector_wrench_in_hand` in the Manipulator State proto …

Update to 5.0.0

---

spot_ros2_control/README.md
spot_ros2_control/launch/spot_ros2_control.launch.py

We can now specify multiple ros2_control controllers to spawn at launch by listing them, comma-separated, in the `robot_controllers` arg. Previously this arg only accepted a single controller name, allowing only a single user-specified controller from the `*_controller_config.yaml` file to be launched.
This was tested by spawning two different custom controllers with different parameters using the `robot_controllers` launch arg, tested on both Mock and real Spot.

Allow spawning of multiple robot controllers via launch arg

---

spot_driver/BUILD.bazel
utilities/set_spot_env.sh

adds a utilities/set_spot_env.sh script that parses the spot_driver/config/spot_ros_example.yaml (or similar) to set the BOSDYN_CLIENT_USERNAME, BOSDYN_CLIENT_PASSWORD, and SPOT_IP environment variables. Removes references to config files from BUILD.bazel file.
ran script on my config/spot_ros_config_DO_NOT_COMMIT.yaml, confirmed env vars set.

[SW-NA] add set_spot_env.sh script, remove references to config file

---

spot_driver/CMakeLists.txt
spot_driver/src/interfaces/rclcpp_parameter_interface.cpp

When building latest main (3aa69ec) with clang-14, `spot_driver` fails to build due to `validateFrameParameter()` being marked `constexpr` but returning a non-literal value (std::optional<std::string> pre-C++20).
By removing `constexpr` from the return type of the function resolves this issue.
Here is the full build error prior to fix: 
`/home/gaddison/sporc_ws3/src/spot_ros2/spot_driver/src/interfaces/rclcpp_parameter_interface.cpp:158:45: error: constexpr function's return type 'std::optional<std::string>' (aka 'optional<basic_string<char>>') is not a literal type
static constexpr std::optional<std::string> validateFrameParameter(const std::string& frame,
^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/optional:663:7: note: 'optional<std::basic_string<char>>' is not …

clang build error: removed constexpr from non-literal value (pre-C++ 20)

---

spot_driver/spot_driver/spot_ros2.py

This PR adds support for **arm velocity control** to Spot robots equipped with arms.
The implementation depends on a corresponding update in `spot_wrapper`:
👉 See [bdaiinstitute/spot\_wrapper#173](https://github.com/bdaiinstitute/spot_wrapper/pull/173) for details.
Earlier related work and references:
* \#540
* \#366
Tested on the **real robot** using a standard **Xbox joystick**.
Planned and completed tests:
For ROS 2 testing guidelines, refer to the [ros\_utilities wiki](https://github.com/bdaiinstitute/ros_utilities/wiki/Testing-guidelines).

Add Arm velocity commands to the Spot

---

spot_driver/config/spot_ros_example.yaml
spot_driver/spot_driver/spot_ros2.py

This builds on the work from #704 by adding a new parameter: `arm_cmd_duration`, similar to `cmd_duration` for base control.
Previously, arm and base commands were sent at the same rate with the same timeout, but this caused issues. Adding a separate parameter for the arm allows better control.
* Tested on the real robot
* Arm commands now work as expected with the new timeout

Added a parameter for arm control

---

spot_driver/config/spot_ros_example.yaml
spot_driver/include/spot_driver/interfaces/parameter_interface_base.hpp
spot_driver/include/spot_driver/interfaces/rclcpp_parameter_interface.hpp
spot_driver/src/images/spot_image_publisher.cpp
spot_driver/src/interfaces/rclcpp_parameter_interface.cpp
spot_driver/src/robot_state/state_publisher.cpp
spot_driver/test/include/spot_driver/fake/fake_parameter_interface.hpp
spot_driver/test/src/test_parameter_interface.cpp

Currently on main, robot state rate is hardcoded to 50 Hz and image publish rate is hardcoded to 15 Hz. This PR makes this info come from ROS parameters (while leaving the default behavior unchanged).

Robot state rate and image rate parameters

---

spot_examples/spot_examples/wasd.py

If robot name is `None` (no namespace), this example crashes. This fixes it :)

Fix wasd example

---

pyproject.toml
spot_ros2_control/CMakeLists.txt
spot_ros2_control/README.md
spot_ros2_control/examples/mixed_level_example.py
spot_ros2_control/examples/set_gripper_gains.py
spot_ros2_control/launch/noarm_squat.launch.py
spot_ros2_control/launch/spot_ros2_control.launch.py
spot_ros2_control/launch/wiggle_arm.launch.py
spot_ros2_control/test/pytests/conftest.py
spot_ros2_control/test/pytests/test_spot_ros2_control.py

I wanted to make an example for the mixed level API in this repo, as a more barebones example that doesn't use any of our internal tooling. 
As a part of this I updated the readme to point to this example and also added mypy checks for the `spot_ros2_control` package which adds a few minor changes to other files.
Arguably this example could also live in `spot_examples`, but I opted to put it in `spot_ros2_control/examples` to keep anything involving low level control isolated in this package.

Example for mixed level API 

---

spot_driver/spot_driver/spot_ros2.py
spot_msgs/CMakeLists.txt
spot_msgs/msg/MobilityParams.msg
spot_msgs/srv/SetStairsMode.srv

The aim of this PR is to update the service `/stair_mode` in order to modify the MobilityParams variable `stairs_mode` instead of the deprecated one `stair_hint`. With this change the robot will be able to be set in stairs mode ON, OFF, AUTO and PROHIBITED.
- Added SetStairsMode.srv
- Modified MobilityParams.msg to include stairs_mode and deleted stair_hint variable on message
- Changed service `/stair_mode` to `/stairs_mode`
- Changed `/stairs_mode` service type to SetStairsMode
- Changed `/stairs_mode` service callback to match the new message type `bosdyn_spot_api_msgs/msg/MobilityParamsStairsMode`
- Compiled without errors
- Launched spot_driver
- Several service calls to the new service
- Tested on real Spot Explorer going upstairs and downstairs. If stairs mode ON or AUTO spot …

Stairs mode improvement

---

Dockerfile
install_spot_ros2.sh

I don't believe `rosdep` is install `QtUiTools`, so I added it to the install script. I'll add it to the Dockerfile and README too.
Please include a summary of the changes made and the relevant ticket or issue.

Add QtUiTools dependency for spot_rviz_plugins
