spot_driver/spot_driver/spot_ros2.py

Trajectory action now works, tested on a Spot. I had to change to a MultiThreaded executor to get it to work properly.

Trajectory fixes

---

spot_driver/spot_driver/spot_ros2.py

Trying to test moving the Spot so fixed this typo.

Bug fix in handle_max_vel.

---

spot_driver/spot_driver/spot_ros2.py

Navigation to action fixed and tested with a real Spot.

Navigation fixes

---

README.md

The readme in the humble branch wasn't updated. Tested code on ubuntu 22.04 and tested code with ros2 humble.

README: update readme instructions for ros2 humble

---

spot_description/package.xml

My participation trophy in contributions :)

fix: updated spot_description exec_depend to be rviz2

---

spot_driver/spot_driver/manual_conversions.py

ROS is annoying in that Pose is different than Transform and such. Another conversion function that is needed.

Another pose conversion function

---

spot_description/launch/standalone_arm.launch.py
spot_description/rviz/standalone_arm.rviz
spot_description/urdf/standalone_arm.urdf.xacro

adds a separate xacro file for the standalone arm with a base link for the purpose of loading in rigid body dynamics and adds the rviz2 launch file for visualization. Fyi, I kept the distance between the actual base origin of spot, and the base for this robot as is,

standlone arm urdf and rviz2 launch file and cofiguration

---

.devcontainer/Dockerfile
.github/workflows/build_docker.yml
.github/workflows/test.yml
README.md

This PR adds a workflow that builds this repo with a docker image built with #39. A few dependencies to the dockerfile are also added to make the build successful.

Add test workflow to CI

---

spot_driver/spot_driver/conversions.py
spot_driver/spot_driver/manual_conversions.py

Also fix adding to protobuf lists (should be `append` was `add`)

Add conversion functions for empty protobufs since they get called

---

spot_driver/spot_driver/publish_cameras.py
spot_driver/spot_driver/ros_helpers.py
spot_driver/spot_driver/spot_ros2.py

[SW-66] Also, exposes "has_arm" as a ros parameter that can be queried via a service client (https://roboticsbackend.com/ros2-global-parameters/)
[SW-66]: https://theaiinstitute.atlassian.net/browse/SW-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SW-62] Publish hand images

---

spot_driver/spot_driver/spot_ros2.py
spot_msgs/CMakeLists.txt
spot_msgs/action/Manipulation.action

This adds a stub for adding support for the manipulation api. Tested on robot.

[WUD-126] Myeatman/manipulation api

---

spot_driver/spot_driver/manual_conversions.py
spot_driver/spot_driver/ros_helpers.py

Fixing problems after moving data conversion functions from ros_helpers to manual_conversions.
Hardware-tested:

[N/A] Quick fix- import errors in manual_conversions

---

spot_driver/spot_driver/spot_ros2.py

- Fixes bug with incorrect goal check for success
- Adds a function to check all feedback status to determine when the action is finished

[N/A] Add all manipulation statuses for handling

---

spot_driver/spot_driver/spot_ros2.py

Got left out when I redid the clean shutdown PR

[N/A] try_shutdown for the external shutdown

---

spot_driver/spot_driver/spot_ros2.py

Given the update from spot wrapper PR https://github.com/bdaiinstitute/spot_wrapper/pull/39. 
Used for testing that PR.
Additionally updated spotwrapper to latest to prevent any miss match

[N/A] Modular docking update for spot_ros2

---

spot_driver/spot_driver/spot_ros2.py

Must be done in tandem with https://github.com/bdaiinstitute/spot_wrapper/pull/42.

[SW 309] Update spot_ros2 in preparate for the modular image PR in spot_wrapper

---

.github/CODEOWNERS

[N/A] Update codeowners

---

spot_driver/spot_driver/spot_ros2.py

[N/A] Fix bug with gripper status check

---

spot_driver/spot_driver/spot_ros2.py

This is incorporating the changes in `spot_wrapper` of https://github.com/bdaiinstitute/spot_wrapper/pull/44 so needs to be updated in tandem with that PR.

Edited spot_ros2 to work with new graphnav

---

install_spot_ros2.sh
spot_driver/spot_driver/conversions.py

This reverts commit 26d26d20eeb46656dc599a1780928d1b26a0719f.

Revert "Updating install script to use ROS2 messages 3.3.2 (#177)"

---

spot_driver/launch/spot_driver.launch.py
spot_driver/spot_driver/ros_helpers.py
spot_driver/spot_driver/spot_ros2.py

A `port` parameter was added to the constructor for `SpotWrapper`. This PR populates it.

[N/A] Hot fix for port parameter for SpotWrapper

---

spot_driver/package.xml

Changes:
- Organized package.xml so easier to see what's in it.
- Added protobuf as a dependency.

[N/A]  Update spot_driver package.xml

---

.github/CODEOWNERS

Added Tiffany and Katie to CODEOWNERs file so they can merge.

[N/A] Added Tiffany and Katie to CODEOWNERS

---

examples/utilities/utilities/simple_spot_commander.py
examples/utilities/utilities/tf_listener_wrapper.py
spot_driver/launch/rviz.launch.py
spot_driver/launch/spot_image_publishers.launch.py
spot_driver/spot_driver/publish_cameras.py

This PR updates some files to our new-style copyright.
N/A, no code changed

[SW-685] Fix spot_ros2 copyrights

---

spot_driver/test/pytests/conftest.py

I was trying to reproduce the testing here but left out the `PowerCommand` because it seemed unnecessary.  Took me a while to realize why it was so important so I added a comment about it :)
None

Add a comment to explain why we need the power command in conftest.py

---

spot_driver/spot_driver/spot_ros2.py

Add API to stop choreography over ROS
Tested by playing dances on robot and then stopping them with the new topic

[N/A] Add stop dance ros trigger

---

LICENSE
spot_description/launch/description.launch.py
spot_description/launch/standalone_arm.launch.py
spot_examples/LICENSE

Added some missing copyright headers, updated some license dates, and added a new license to `spot_examples`
N/A

[SW-733] Update licenses

---

README.md

The arm services were just renamed, this updates the readme

[N/A] Update readme with updated service names

---

spot_msgs/CMakeLists.txt

Suppress CMP0148 so I get less spammy warnings during bdai build.
Just CI

Suppress CMake warnings

---

.devcontainer/Dockerfile

Forgot to update this for the main change to 4.0.2. This makes it so that our CI tests use the new package versions.

[N/A] Update dockerfile for 4.0.2

---

spot_driver/spot_driver/spot_ros2.py

Follow-up to #347. Depends on https://github.com/bdaiinstitute/spot_wrapper/pull/118.
Tested downstream as there are no Spot CAM specific tests in this repo. Should there be?

Forward port and certs to `SpotCamWrapper`

---

spot_description/urdf/spot_arm_macro.urdf
spot_description/urdf/spot_macro.xacro

Updates the URDF with effort limits provided by BD.
We don't know any more specifics for updating the velocity limits so those are left at the same for now.

Update joint effort values in URDF

---

spot_driver/spot_driver/calibrated_reregistered_hand_camera_depth_publisher.py

Just adding shebang so that you can ros2 run .... the file with no issues
ros2 ran the file

[SW-1245]: Need shebang to ros2 run script

---

README.md

Update the flag in the readme to match the updated version in spot wrapper
in 
https://github.com/bdaiinstitute/spot_wrapper/pull/137
and
https://github.com/bdaiinstitute/spot_wrapper/pull/136
Reran calibration script with updated flag pattern

Update Calibration Arg Parser Flag in README

---

spot_ros2_control/examples/src/joint_command_passthrough.cpp

Makes the topic names parameters you can pass in (as they should be)
Tested on robot

Parameterize joint_command_passthrough parameters

---

README.md
spot_driver/spot_driver/calibrated_reregistered_hand_camera_depth_publisher.py

Add how to conduct a drop in test of the calibrated gripper results from 
https://github.com/bdaiinstitute/spot_ros2/pull/455
Ran the drop in test as described in the README, found that the quality visually improves while preserving scaling and rough position

Calibration: Show Sanity Check in main README

---

spot_driver/spot_driver/spot_ros2.py

This adds a subscriber similar to "arm_joint_commands" that listens to poses over joint angles.
Goes along with `spot_wrapper` PR here https://github.com/bdaiinstitute/spot_wrapper/pull/145
Tested on Robot with various poses and different ref frames

[MAPLE-743] Add Cartesian arm pose commands

---

spot_driver/spot_driver/spot_ros2.py

In order to get smooth streaming of hand poses, this adds in a non blocking flag to the hand posing function

[MAPLE-743] Add hand posing non blocking option

---

install_spot_ros2.sh

Fixes https://github.com/bdaiinstitute/spot_ros2/issues/621
Tested with Docker and `--no-cache`
Maybe it would be good to disable cache in the CI pipelines to catch these issues?

Fixes rosdep distro 

---

README.md
spot_ros2_control/README.md

Added some guidance on using the mixed level API in the `spot_ros2_control` readme
Also did a few AI Institute --> RAI Institute name changes 

[SW-2238] Spot mixed api documentation

---

spot_driver/README.md
spot_driver/config/spot_ros_example.yaml
spot_driver/spot_driver/spot_ros2.py

Adds a velodyne point cloud publisher for users with a Spot EAP module. The code is largely copied from `spot_ros`'s ROS 1 implementation: https://github.com/heuristicus/spot_ros/blob/master/spot_driver/src/spot_driver/spot_ros.py
See: https://github.com/bdaiinstitute/spot_ros2/issues/542

[N/A] support for velodyne on spot EAP

---

spot_driver/spot_driver/spot_ros2.py

Change to the driver to fix #669 to be used in tandem with the fix to the wrapper [here](https://github.com/bdaiinstitute/spot_wrapper/pull/169)

lidar data handling fix

---

MODULE.bazel
deps/python/BUILD.bazel
deps/python/locks/requirements_main_x86_64.lock
deps/python/requirements_main.in
deps/spot_description/BUILD.bazel
deps/spot_description/requirements.in
deps/spot_description/spot_description.BUILD.bazel
deps/spot_wrapper/spot_wrapper.BUILD.bazel
jammy.yaml

Bazelized spot_description
Run `bazel run @spot_description//:launch_spot_with_arm` to launch rviz and pose control widget.

[SW-2905] Bazelize spot_description

---

MODULE.bazel
deps/python/locks/requirements_main_aarch64.lock
deps/python/locks/requirements_main_x86_64.lock
deps/python/requirements_main.in
jammy.yaml
spot_examples/BUILD.bazel
spot_examples/spot_examples/arm_simple.py
spot_examples/spot_examples/arm_with_body_follow.py
spot_examples/spot_examples/hello_spot.py
spot_examples/spot_examples/robot_commander.py
spot_examples/spot_examples/send_inverse_kinematics_requests.py
spot_examples/spot_examples/simple_sub.py
spot_examples/spot_examples/spot_in_circle.py
spot_examples/spot_examples/walk_forward.py
spot_examples/spot_examples/wasd.py

Please include a summary of the changes made and the relevant ticket or issue.

[SW-2908] bazelize spot examples

---

spot_driver/EyeInHandCalibration.md

I tried running this on robot today. This PR fixes a minor typo in the README 
-[x] Ran the script successfully on robot

[N/A] fixes typo in eye in hand calibration instruction

---

spot_driver/test/pytests/test_stair_mode.py

Follow up to https://github.com/bdaiinstitute/spot_ros2/pull/718 -- fixes `test_stair_mode`

Fix Stairs Mode Test
